stages:
  load_data:
    cmd: python src/stage01_Load_Save.py --config=config/config.yaml
    deps:
      - src/stage01_Load_Save.py
      - src/utils/ultility_Methods.py
      - config/config.yaml

    outs:
      - artifacts/raw_local_dir/data.csv




