stages:
  load_data:
    cmd: python src/stage01_Load_Save.py --config=config/config.yaml
    deps:
      - src/stage01_Load_Save.py
      - src/utils/ultility_Methods.py
      - config/config.yaml

    outs:
      - artifacts/raw_local_dir/base_data.csv

  split_save_data:
    cmd: python src/stage02_SplittingData.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage02_SplittingData.py
      - src/utils/ultility_Methods.py
      - config/config.yaml
      - params.yaml
      - artifacts/raw_local_dir/base_data.csv

    outs:
      - artifacts/split_data/x_test.csv
      - artifacts/split_data/x_train.csv
      - artifacts/split_data/y_test.csv
      - artifacts/split_data/y_train.csv







